require('../resources/manifest.json')

require('normalize.css/normalize.css')
require('font-awesome/css/font-awesome.css')
require('emoji/lib/emoji.css')
require('../stylesheets/styles.scss')
require('./components/Button/styles.scss')
require('./components/AuthPanel/styles.css')
require('./containers/Popup/styles.scss')
require('./containers/Options/styles.scss')
require('./global.scss?raw')

require('../assets/icon-128.png')
require('../assets/icon-16.png')
require('../assets/icon-48.png')
